export const GV_REQUEST_NEXT_PROPERTIES = 'GV_REQUEST_NEXT_PROPERTIES';
export const GV_REQUEST_NEXT_PROPERTIES_DONE = 'GV_REQUEST_NEXT_PROPERTIES_DONE';
export const GV_SORT_PROPERTIES = 'GV_SORT_PROPERTIES';
